### ISSUE TITLE
Открывание домофона

### ISSUE THREAD

**Issue by ilyafdtv** [Muxee4ka/ucams_home_assistant#1]
Отлично работают камеры, спасибо!
Добавьте еще, пожалуйста, открывание домофона/калитки/шлагбаума

**Comment by Muxee4ka** [comment]
> Отлично работают камеры, спасибо! Добавьте еще, пожалуйста, открывание домофона/калитки/шлагбаума

К сожалению нет возможности исследовать этот функционал, потому что у нас только камеры от УфыНет...

**Comment by ilyafdtv** [comment]
> > Отлично работают камеры, спасибо! Добавьте еще, пожалуйста, открывание домофона/калитки/шлагбаума
> 
> К сожалению нет возможности исследовать этот функционал, потому что у нас только камеры от УфыНет...

В веб-интерфейсе УфаНет открывания у нас тоже нет. Оно работает в андроид-приложении через HTTP запросы:
GET https://dom.ufanet.ru/api/v0/skud/shared/*номер домофона*/open/ HTTP/1.1
Authorization: *JWT или Beurer token*
Host: dom.ufanet.ru
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.14.9

Я через CURL запускал открывание такими запросами, но не смог разобраться как обновлять токены и сделать это в виде приложения к ХА. Готов прислать и другие подробные данные при необходимости..

**Comment by Muxee4ka** [comment]
> Готов прислать и другие подробные данные при необходимости..

Нужна вся цепочка запросов-ответов: 
авторизация -> получение списка доступных устройств -> возможные действия с устройствами..
